Use elemHashes in lookup
IntersectMBO/lsm-tree pull request #246
Opened 2024-06-11 12:59 UTC by phadej

2024-06-14 09:21 UTC, jorisdral requested changes
Net time for bloom filter queries in the lookup macro-benchmark went from 3.55s down to 1.93s. That's a pretty good improvement!

2024-06-14 09:21 UTC, jorisdral commented on bloomfilter/src/Data/BloomFilter/Hash.hs
> +    alignmentOfType# _ = 64#
These are in number of bytes

```suggestion
    sizeOfType# _ = 16#
    alignmentOfType# _ = 8#
```

I didn't immediately spot this until I ran `primLaws` tests from `quickcheck-classes`. Feel free to include this in the tests if you think it's useful:

```haskell

-------------------------------------------------------------------------------
-- Prim
-------------------------------------------------------------------------------

instance Arbitrary (CheapHashes a) where
  arbitrary = CheapHashes <$> arbitrary <*> arbitrary
  shrink (CheapHashes x y) = uncurry CheapHashes <$> shrink (x, y)

deriving instance Eq (CheapHashes a)

prop_primLaws :: Property
prop_primLaws = ioProperty $
    lawsCheck $ primLaws (Proxy @(CheapHashes Void))

testLawsCheck :: Laws -> TestTree
testLawsCheck (Laws className properties) =
    testGroup className [
        testProperty name prop
      | (name, prop) <- properties
      ]
```

2024-06-14 11:18 UTC, jorisdral approved these changes
Let's squash and merge

2024-06-17 12:00 UTC, dcoutts commented
I tried using this in the macrobenchmark for bloom filters only (not the whole lookup) and get odd results with the allocations. The time is good though, and faster than the one-by-one. That mystery doesn't have to be solved for this PR though.

2024-06-17 12:22 UTC, merged