Remove Totality requirement for ResolveValue
IntersectMBO/lsm-tree pull request #333
Opened 2024-08-12 08:52 UTC by mheinzel

2024-08-12 14:16 UTC, jorisdral requested changes
LGTM. Small but unrelated comment below

2024-08-12 14:16 UTC, jorisdral commented on src/Database/LSMTree/Monoidal.hs
It might be better to move the `ResolveValue Word64` instance to the test suite, since it might/will conflict with user instance. Or, alternatively, you can use a newtype in the style of `Data.Monoid.Sum` as an example, and it might be useful as a modifier as well

2024-08-12 22:06 UTC, mheinzel commented on src/Database/LSMTree/Monoidal.hs
I initially also wanted to provide an instance for `Sum`, but it's trickier than I thought. `resolveDeserialised` requires an instance `SerialiseValue (Sum a)` (and I didn't want to coerce things based on `SerialiseValue a` because the instances might disagree), but I'm not sure we generally want to have `instance SerialiseValue a => SerialiseValue (Sum a)`. But if we don't, users would have to define an orphan instance for e.g. `SerialiseValue (Sum Foo)`, which seems wrong.

2024-08-12 22:08 UTC, mheinzel commented on src/Database/LSMTree/Monoidal.hs
I can provide instances `SerialiseValue (Sum Word64)` and  `ResolveValue (Sum Word64)` specifically, maybe that's an okay compromise?

2024-08-13 18:36 UTC, recursion-ninja commented on src/Database/LSMTree/Monoidal.hs
I added the `SerialiseValue (Sum Word64)` and `ResolveValue (Sum Word64)` instances. I squashed the commit and re-based with `main` in anticipation of merging.

2024-08-14 18:55 UTC, recursion-ninja commented on src/Database/LSMTree/Monoidal.hs
Per a discussion with @mheinzel:

Regarding the instance `SerialiseValue a => SerialiseValue (Sum a)`, it essentially states that the `Sum` newtype is transparent to serialization. This assertion is not unreasonable, as it is highly improbable one would serialize `Sum a` differently than `a`.

Hence we can have the more useful polymorphic instance: 
```
instance (Num a, SerialiseValue a) => ResolveValue (Sum a)
```

2024-08-15 17:31 UTC, mheinzel reviewed
One last detail, then we can merge.

2024-08-15 17:31 UTC, mheinzel commented on test/Test/Database/LSMTree/Monoidal.hs
> +    [ testGroup "Word64" (allProperties @Word64)
Ah, I thought we would just use the existing instance for `ResolveValue (Sum Word64)` instead of defining an orphan instance.

2024-08-19 19:59 UTC, merged