Define cursor API
IntersectMBO/lsm-tree pull request #344
Opened 2024-08-21 07:58 UTC by mheinzel

# Description

Defines the public API for cursors. The implementation will follow soon, but I decided to split the work into small PRs, so individual aspects can be reviewed and merged separately. For example, based on this PR, one could already start integrating the new cursor API into the quickcheck-lockstep tests.

I decided to rename RangeLookupResult, since it will be used for cursor reads, too. Generally it is useful for returning entries when their keys are not already known, which is everything except for (point) lookups.

# Checklist

- [x] Read our contribution guidelines at [CONTRIBUTING.md](https://github.com/IntersectMBO/lsm-tree/blob/main/CONTRIBUTING.md), and make sure that this PR complies with the guidelines.

2024-08-21 13:13 UTC, jorisdral requested changes
Just some small things to address, and then we can merge

2024-08-21 13:13 UTC, jorisdral commented on src/Database/LSMTree/Normal.hs
We should extend/update the `$resourcemanagement`, `$exception-safety`, and `$concurrency` documentation sections.

2024-08-21 14:26 UTC, mheinzel commented on test/Test/Database/LSMTree/Class/Monoidal.hs
> +rangeLookupResultKey (FoundInQuery k _) = k
Ah, yes, I didn't grep for the lower case version. Thanks!

2024-08-21 14:29 UTC, mheinzel commented on src/Database/LSMTree/Normal.hs
I don't know how helpful it would be to add "and cursors" every time the docs talk about table handles there. Maybe in the beginning once say "(and similarly for cursors)" or at the end have a short sentence that all of this also applies to cursors?

2024-08-21 15:42 UTC, jorisdral commented on src/Database/LSMTree/Normal.hs
True, there is some duplication there, but I think it's minor

2024-08-21 17:14 UTC, merged

2024-08-29 14:35 UTC, dcoutts reviewed
API looks good.