Refactoring APIs involving HasIO & HasBlockIO
IntersectMBO/lsm-tree pull request #418
Opened 2024-10-04 21:56 UTC by recursion-ninja

# Description

Refactors the usage of `HasFS` and `HasBlockIO` abstractions, by "internalizing" the values within the data-types which require them. This noticeably cleans up the module API interface, removing the requirement of manually passing `HasFS` and `HasBlockIO` values across multiple abstraction layers of the `LSMTree`. The `HasFS` and `HasBlockIO` are now required from the user *only* when creating a new `RunBuilder, rather than required for most functions exposed by a half dozen module's interfaces.

*NB: Still needs to be rebased with `main` which will require another sizable chunk of time.*

2024-10-09 08:33 UTC, jorisdral requested changes
A few small changes to make, and then we can merge this

2024-10-09 08:33 UTC, jorisdral commented on src/Database/LSMTree/Internal/Run.hs
> +  => RunDataCaching
```suggestion
fromMutable :: 
     (MonadFix m, MonadST m, MonadSTM m, MonadThrow m)
  => RunDataCaching
```

2024-10-09 08:33 UTC, jorisdral commented on src/Database/LSMTree/Internal/RunBuilder.hs
> +data RunBuilder m s h = RunBuilder {
We'll never use any `s` other than `PrimState m`
```suggestion
data RunBuilder m h = RunBuilder {
```

2024-10-09 08:33 UTC, jorisdral commented on src/Database/LSMTree/Internal/RunBuilder.hs
> +    , runBuilderHandles    :: {-# UNPACK #-} !(ForRunFiles (ChecksumHandle s h))
```suggestion
    , runBuilderHandles    :: {-# UNPACK #-} !(ForRunFiles (ChecksumHandle (PrimState m) h))
```

2024-10-09 08:33 UTC, jorisdral commented on src/Database/LSMTree/Internal/RunBuilder.hs
> +--
```suggestion
```

2024-10-10 09:04 UTC, dcoutts commented
I'll pick this one up...

2024-10-10 10:09 UTC, dcoutts approved these changes
LGTM now!

2024-10-10 15:45 UTC, merged